### ISSUE TITLE
Mark homework1, exercise 1&2 of Anqi Shi

### ISSUE THREAD

**Issue by anqis929** [anqis929/stat679#2] opened 2016-10-08 01:05 UTC
4e7c05e63184654525e0eaa85603b64c68b38359
# This commit modified my README.md file

fcb3f7a170ba42a3c3ee8f755e2b5a9cdc5b8b98
# This commit uploaded my full HW folder (I uploaded a folder only have code files in it and uploaded this #one couple days ago, hope this doesn't count as late HW)

Thank you Professor @cecileane

**Comment by cecileane** [comment] 2016-10-08 21:54
Hi Anqi,

Good job! Below is some feedback, that you might use for future homework.

Your normalization script is lean and with comments, that's great. It only does the `.log` files however, not the `.out` files. Ohoh, I see that this part is in your other script! There could be better organization. Your readme files could provide more information to help the reader reproduce your analysis (such as from which directory each script should be called).

Your final summary file lacks a header. You can visualize it nicely in a browser [here](https://github.com/anqis929/stat679/blob/master/hw1/hw1EX2.csv). The first line, in bold, is supposed to have a header with a name for each column. The first column should be named "analysis", the second, "h" and the third "CPUtime". If you could have this header for exercise 3, it would be great!

An important limitation of your summarizing script is that it can only run on your own machine, because of this line:

`cd /Users/Macpro/Desktop/stat679HW/stat679/hw1`

If you reorganize your folders in a year (say), the script would easily no longer work for yourself. It is not "portable". To avoid this limitation, use relative paths. For example, say in your `readme` file that the script should be run in the folder `stat679/` (whereever this folder might be on my machine, or on your machine next year), then have the script do `cd hw1/`, where the path `hw1/` is relative to `stat679/`. So I modified this path in your script (also removed the first part to rename the `.out` files) and ran it. The result summary was then twice as long as it should have been:

``` shell
$ bash summarizeSNaQres.sh
$ cat hw1EX2.csv
bT1, 0, 103354.760381735
net1_snaq, 1, 11648.984309726
newtry1, 1, 88579.306341032
timetest01_snaq, 1, 16688.01510346
timetest02_snaq, 1, 37137.96354747
timetest03_snaq, 1, 12630.994448551
timetest04_snaq, 1, 21942.346502542
timetest05_snaq, 1, 23949.375026384
timetest06_snaq, 1, 39287.796202476
timetest07_snaq, 1, 29822.147601027
timetest08_snaq, 1, 51589.342317181
timetest09_snaq, 1, 34831.465925074
timetest10_snaq, 1, 29394.463493788
timetest11_snaq, 1, 67926.502059791
timetest12_snaq, 1, 18935.630572383
timetest13_snaq, 1, 31456.993676184
bT1, 0, 103354.760381735
net1_snaq, 1, 11648.984309726
newtry1, 1, 88579.306341032
timetest01_snaq, 1, 16688.01510346
timetest02_snaq, 1, 37137.96354747
timetest03_snaq, 1, 12630.994448551
timetest04_snaq, 1, 21942.346502542
timetest05_snaq, 1, 23949.375026384
timetest06_snaq, 1, 39287.796202476
timetest07_snaq, 1, 29822.147601027
timetest08_snaq, 1, 51589.342317181
timetest09_snaq, 1, 34831.465925074
timetest10_snaq, 1, 29394.463493788
timetest11_snaq, 1, 67926.502059791
timetest12_snaq, 1, 18935.630572383
timetest13_snaq, 1, 31456.993676184
```

That's because your script is missing a line at the beginning to write the header and to _erase_ whatever was on this file in the first place. You could fix this for the next exercise.

Last note on the summary file: it should not have any spaces. The commas are used to separate columns: no need for spaces. If there is a space, it will be interpreted to be part of the entries, which is typically not desired.

You have a clever use of `cut` with various delimiters and of parameter substitution. Unfortunately, you did not get much practice with `grep` as a result. It was one of the main goals of this homework. You used _extended_ regular expressions only once (based on the example from the course notes). Learning to use extended regular expressions would be useful for all other languages, not just the shell.

It looks like you got experience with a merge commit in git: due to uploading files from the browser, which de-synchronize the history of your project on github and that on your laptop. But then you merge your history on your laptop and on github, so all good! You still have several `.DS_Store` files tracked by git... not good. Make sure to do `git status` in the future, to check what's being changed, added, or not tracked before you make a commit.

**Closed as completed by cecileane** 2016-10-08 21:54 UTC
